sonar.projectKey=mulesoft-emu.ms-ic-connector-tes.gec
sonar.projectName=MS Universal Connectivity - Tes Connector
sonar.github.repository=mulesoft-emu/ms-ic-connector-tes
sonar.sourceEncoding=UTF-8

sonar.sources=tes-connectivity-model/src/main/dw, tes-flow-connector-model/src/main/dw, tes-anypoint-connector-model/src/main/dw
sonar.tests=tes-connectivity-model/src/test/dw, tes-flow-connector-model/src/test/dw, tes-anypoint-connector-model/src/test/dw
sonar.coverageReportPaths=tes-connectivity-model/target/data-weave-test-reports/coverage/sonar.xml, tes-flow-connector-model/target/data-weave-test-reports/coverage/sonar.xml, tes-anypoint-connector-model/target/data-weave-test-reports/coverage/sonar.xml
sonar.verbose=true
sonar.python.file.suffixes=.dwl
sonar.exclusions=**/Connector.dwl, **/Types.dwl
